In [11]:
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Load the dataset
data = pd.read_csv("kmeans_Q1.csv")
# fig = plt.figure()
# ax = fig.add_subplot(111,projection='3d')
# ax.scatter(data['Points'],data['Assists'],data['Rebounds'],color='b')

# ax.set_xlabel('Points')
# ax.set_ylabel('Assists')
# ax.set_zlabel('Rebounds')
print(np.array(data))




[[18.  3. 15.]
 [19.  4. 14.]
 [14.  5. 10.]
 [14.  4.  8.]
 [11.  7. 14.]
 [20.  8. 13.]
 [28.  7.  9.]
 [30.  6.  5.]
 [31.  9.  4.]
 [35. 12. 11.]
 [33. 14.  6.]
 [25.  9.  5.]
 [25.  4.  3.]
 [27.  3.  8.]
 [29.  4. 12.]
 [30. 12.  7.]
 [19. 15.  6.]
 [23. 11.  5.]]


In [10]:
class KMeansModel():
    def __init__(self,data,k_max):
        self.data = data
        self.k_max = k_max
        self.history = []
    def fit(self):
        for k in range(2,self.k_max+1):
            pass
    def initialize_centroid(self,k):
        return self.data[np.random.choice(self.data.shape[0],k,replace=False)] 
    def assign_labels(self, centroids):
        
    



model = KMeansModel(data)

[18. 19. 14. 14. 11. 20. 28. 30. 31. 35. 33. 25. 25. 27. 29. 30. 19. 23.]
[ 3.  4.  5.  4.  7.  8.  7.  6.  9. 12. 14.  9.  4.  3.  4. 12. 15. 11.]
